name: d_py38_pv3vis
dependencies:
    - python=3.8
    - jupyter
    - matplotlib
    - pandas
    - plotly
    - sqlalchemy
    - seaborn
    - xlrd
    - openpyxl
    - psycopg2
    - pip:
        - pvlib